shops:
  shop:
    title: '&6GT:NH Token Shop'
    rows: 6
    auto-close: true
    items:
      '0':
        item: IRON_BLOCK
        description: '&c&lVIP_2x_Months &4----------------|&bExtra_commands|&eSpecial_kit|&b8_homes|&4----------------|&aPrice:&a_%price%_Tokens|&4----------------|&dBalance:_%tokens%_Tokens'
        cost: 190
        message: '&bThank you for purchasing VIP, %player%! price &c%price% tokens'
        commands:
        - 'bc %player% just purchased VIP, thank you!'
        - 'eco give %player% 6500'
        - 'lp user %player% parent addtemp vip 2mo'
